version: '3'
services:

  #stores tweets in a mongodb
  tweets_collector:
    build: tweets_collector/
    volumes:
    - ./tweets_collector/:/app
    depends_on:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - "27017:27017"

  # Add Postgres to docker-compose
  postgresdb:
    image: postgres
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_USER=pbamoo
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=mongodb


  # read lyrics from mongodb and store them in Postgres
  etl:
   build: etl_job/
   volumes:
   - ./etl_job/:/app
   depends_on:
   - mongodb
